### ISSUE TITLE
Beta 1 Roadmap

### ISSUE THREAD

**Issue by MotoLegacy** [thyjukki/NZP-Reboot#31]
**List of bug fixes/features I'd like to have finished before making a first release. Bugs will be checked off as they are fixed/added.**

_PSP Bugs_
- [x] Precaching issues
- [x] No support for 2nd vmodel
- [ ] Menu inconsistent with PC!

_PC Bugs_
- [ ] Spr32 support borked
- [ ] MDL rendermodes also borked
- [ ] Menu inconsistent with PSP!
- [ ] Multiplayer needs thorough testing 

_Misc. Bugs_
- [ ] Pausing doesn't kill sounds
- [x] Zombies should stop moaning when killed and play the death sound (easy!)
- [ ] Explosives/crawlers break the zombie counter, rounds start early
- [ ] Zombies get stuck in a window if more than one is trying to mantle
- [x] Bouncing Betties need tweaked
- [ ] Dual Wield weapons fight over weapon frame control

_Mystery Box_
These are easy, and I already have the model/frames for them. I just forget how to use the Blender qmdl exporter!!
- [ ] Teddy bear sitting animation for teleport spot (for consistencies sake!)
- [ ] Mystery box needs leave animation

_Weapons_
- [ ] Raygun's skin gets confused, sometimes has PaP skin
- [ ] 'Special' weapons needs ADS animations (50% done)
- [ ] Panzer & Type 100 muzzleflashes need adjusted

**Comment by iPOUNDcorpses** [comment]
this is Awesome. ive tried to get on the NZP forums for just about a year now my account was never Verified. sadly. but I'm glad I found this. I downloaded the reboot but there is no Progs.dat in the psp version so I can't play it unfortunately I'm so glad too see you guy's still working on this I'd love to see something like this for Solitude Reborn.

**Comment by DerpedCrusader** [comment]
> this is Awesome. ive tried to get on the NZP forums for just about a year now my account was never Verified. sadly. but I'm glad I found this. I downloaded the reboot but there is no Progs.dat in the psp version so I can't play it unfortunately I'm so glad too see you guy's still working on this I'd love to see something like this for Solitude Reborn.

Did you read the readme? you need to compile the code to get the progs.dat

**Comment by blubs** [comment]
Best of luck trying this out!
Let me know if you need help with anything.

**Comment by iPOUNDcorpses** [comment]
I did figure it out thankfully I was having problems with the Exe tho I compiled it followed the path & the prog.dat wasnt there I did it over & over & then I started to think maybe I needed to provide the progs.src files but that didn't make sense cause they were all there already.. so I re extracted the entire file opened the exe back up hit compIle closed the exe went to the psp/nzp folder & there it was lol I've been playing it for the past couple days now & you guys did a fantastic job I will definitely be looking out for any bugs/glitches that aren't already present here. I really look forward to any further progress you guys make keep up the great work!
